# PIPELINE DEFINITION
# Name: pipeline-with-custom-path-artifact
# Description: custom path task
components:
  comp-validate-custom-artifact-path:
    executorLabel: exec-validate-custom-artifact-path
    inputDefinitions:
      parameters:
        num:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      artifacts:
        out_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-validate-custom-artifact-path:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - validate_custom_artifact_path
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.6'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef validate_custom_artifact_path(num: int, out_dataset: Output[Dataset]):\n\
          \    with open(out_dataset.path, 'w') as f:\n        f.write(str(2 * num))\n\
          \    out_dataset._set_path('/etc/test/file/path')\n\n    if out_dataset.path\
          \ != '/etc/test/file/path':\n        raise ValueError(f\"File path is {out_dataset.path}\
          \ but should be '/etc/test/file/path'.\")\n    if out_dataset.custom_path\
          \ != '/etc/test/file/path':\n        raise ValueError(f\"File uri is {out_dataset.custom_path}\
          \ but should be '/etc/test/file/path'.\")\n\n"
        image: your-registry/kfp-base-image:python:3.11
pipelineInfo:
  description: custom path task
  name: pipeline-with-custom-path-artifact
root:
  dag:
    tasks:
      validate-custom-artifact-path:
        cachingOptions: {}
        componentRef:
          name: comp-validate-custom-artifact-path
        inputs:
          parameters:
            num:
              runtimeValue:
                constant: 1.0
        taskInfo:
          name: validate-custom-artifact-path
schemaVersion: 2.1.0
sdkVersion: kfp-2.14.6
